eng = [
    {"ID": "E4ENGA01", "Desc": "인사하기"},
    {"ID": "E4ENGA02", "Desc": "소개하기"},
    {"ID": "E4ENGA03", "Desc": "감정 표현하기"},
    {"ID": "E4ENGA04", "Desc": "날씨 표현하기"},
    {"ID": "E4ENGA05", "Desc": "개수 표현하기"},
    {"ID": "E4ENGA06", "Desc": "능력 여부 표현하기"},
    {"ID": "E4ENGA07", "Desc": "때와 관련된 표현하기"},
    {"ID": "E4ENGA08", "Desc": "물건의 주인이나 소유 확인하기"},
    {"ID": "E4ENGA09", "Desc": "물건의 위치 파악하기"},
    {"ID": "E4ENGA10", "Desc": "제안하기"},
    {"ID": "E4ENGA11", "Desc": "물건 구입하기"},
    {"ID": "E4ENGA12", "Desc": "행동 묘사하기"},
    {"ID": "E6ENGA01", "Desc": "소개하기"},
    {"ID": "E6ENGA02", "Desc": "대상의 특징 묘사하기"},
    {"ID": "E6ENGA03", "Desc": "길 안내하기"},
    {"ID": "E6ENGA04", "Desc": "때와 관련된 표현하기"},
    {"ID": "E6ENGA05", "Desc": "물건의 주인이나 소유 확인하기"},
    {"ID": "E6ENGA06", "Desc": "물건 구입하기"},
    {"ID": "E6ENGA07", "Desc": "감정 표현하기"},
    {"ID": "E6ENGA08", "Desc": "경험이나 계획 표현하기"},
    {"ID": "E6ENGA09", "Desc": "전화 대화하기"},
    {"ID": "E6ENGA10", "Desc": "제안하기"},
    {"ID": "E6ENGA11", "Desc": "다양한 문화 알기"},
    {"ID": "M3ENGA01", "Desc": "소개하기"},
    {"ID": "M3ENGA02", "Desc": "좋아하는 것 표현하기"},
    {"ID": "M3ENGA03", "Desc": "관심 및 원하는 것 표현하기"},
    {"ID": "M3ENGA04", "Desc": "묘사하기"},
    {"ID": "M3ENGA05", "Desc": "안부 표현하기"},
    {"ID": "M3ENGA06", "Desc": "감사 표현하기"},
    {"ID": "M3ENGA07", "Desc": "감정 표현하기"},
    {"ID": "M3ENGA08", "Desc": "의견 교환하기"},
    {"ID": "M3ENGA09", "Desc": "요청하기"},
    {"ID": "M3ENGA10", "Desc": "허락 구하고 답하기"},
    {"ID": "M3ENGA11", "Desc": "계획 표현하기"},
    {"ID": "M3ENGA12", "Desc": "길 찾기"},
    {"ID": "M3ENGA13", "Desc": "약속 정하기"},
    {"ID": "M3ENGA14", "Desc": "대화 상황 파악하기"},
    {"ID": "M3ENGA15", "Desc": "물건 사고 팔기"},
    {"ID": "M3ENGA16", "Desc": "이유 표현하기"},
    {"ID": "M3ENGA17", "Desc": "문제 해결하기"},
    {"ID": "M3ENGA18", "Desc": "경험 표현하기"},
    {"ID": "M3ENGA19", "Desc": "과거 사실 표현하기"},
    {"ID": "M3ENGA20", "Desc": "자료 설명하기"},
    {"ID": "M3ENGA21", "Desc": "관용어구/속담/명언 활용하기"},
    {"ID": "H1ENGA01", "Desc": "소개하기"},
    {"ID": "H1ENGA02", "Desc": "정보 교환하기"},
    {"ID": "H1ENGA03", "Desc": "의견 교환하기"},
    {"ID": "H1ENGA04", "Desc": "시각 자료 활용하기"},
    {"ID": "H1ENGA05", "Desc": "감정 공유하기"},
    {"ID": "H1ENGA06", "Desc": "경험 공유하기"},
    {"ID": "H1ENGA07", "Desc": "계획 공유하기"},
    {"ID": "H1ENGA08", "Desc": "도움 주고 받기"},
    {"ID": "H1ENGA09", "Desc": "이해 전략 적용하기"},
    {"ID": "E4ENGA01B01", "Desc": "때에 따른 인사하기"},
    {"ID": "E4ENGA01B02", "Desc": "안부 묻고 답하기"},
    {"ID": "E4ENGA02B01", "Desc": "자기 소개하기"},
    {"ID": "E4ENGA02B02", "Desc": "다른 사람 소개하기"},
    {"ID": "E4ENGA03B01", "Desc": "감정 묻고 답하기"},
    {"ID": "E4ENGA03B02", "Desc": "상태 묻고 답하기"},
    {"ID": "E4ENGA04B01", "Desc": "날씨 묻고 답하기"},
    {"ID": "E4ENGA05B01", "Desc": "원하는 개수 묻고 답하기"},
    {"ID": "E4ENGA06B01", "Desc": "능력 묻고 답하기"},
    {"ID": "E4ENGA06B02", "Desc": "능력 표현하기"},
    {"ID": "E4ENGA06B03", "Desc": "능력 부인하기"},
    {"ID": "E4ENGA07B01", "Desc": "시각 묻고 답하기"},
    {"ID": "E4ENGA07B02", "Desc": "요일 묻고 답하기"},
    {"ID": "E4ENGA08B01", "Desc": "물건의 주인 묻고 답하기"},
    {"ID": "E4ENGA08B02", "Desc": "물건 소유 확인하기"},
    {"ID": "E4ENGA09B01", "Desc": "물건의 위치 묻고 답하기"},
    {"ID": "E4ENGA09B02", "Desc": "위로 표현하기"},
    {"ID": "E4ENGA09B03", "Desc": "감사 표현하고 답하기"},
    {"ID": "E4ENGA10B01", "Desc": "제안하고 답하기"},
    {"ID": "E4ENGA10B02", "Desc": "음식 권유하고 답하기"},
    {"ID": "E4ENGA10B03", "Desc": "지시 표현하기"},
    {"ID": "E4ENGA10B04", "Desc": "금지 표현하기"},
    {"ID": "E4ENGA11B01", "Desc": "원하는 물건 묻고 답하기"},
    {"ID": "E4ENGA11B02", "Desc": "물건의 이름 묻고 답하기"},
    {"ID": "E4ENGA11B03", "Desc": "가격 묻고 답하기"},
    {"ID": "E4ENGA12B01", "Desc": "현재의 행동 묻고 답하기"},
    {"ID": "E4ENGA12B02", "Desc": "도움 요청하고 답하기"},
    {"ID": "E4ENGA12B03", "Desc": "허락 요청하고 답하기"},
    {"ID": "E6ENGA01B01", "Desc": "출신지 묻고 답하기"},
    {"ID": "E6ENGA01B02", "Desc": "좋아하는 것 묻고 답하기"},
    {"ID": "E6ENGA01B03", "Desc": "장래희망 묻고 답하기"},
    {"ID": "E6ENGA01B04", "Desc": "학년 묻고 답하기"},
    {"ID": "E6ENGA01B05", "Desc": "이름 철자 묻고 답하기"},
    {"ID": "E6ENGA02B01", "Desc": "인물의 외양 묘사하기"},
    {"ID": "E6ENGA02B02", "Desc": "인물의 특징 묘사하기"},
    {"ID": "E6ENGA02B03", "Desc": "두 대상 비교하기"},
    {"ID": "E6ENGA03B01", "Desc": "주의 끌기"},
    {"ID": "E6ENGA03B02", "Desc": "길 묻고 답하기"},
    {"ID": "E6ENGA03B03", "Desc": "찾아가는 방법 묻고 답하기"},
    {"ID": "E6ENGA04B01", "Desc": "일과 묻고 답하기"},
    {"ID": "E6ENGA04B02", "Desc": "날짜 묻고 답하기"},
    {"ID": "E6ENGA04B03", "Desc": "특정일 묻고 답하기"},
    {"ID": "E6ENGA05B01", "Desc": "물건의 주인 묻고 답하기"},
    {"ID": "E6ENGA05B02", "Desc": "감사 표현하기"},
    {"ID": "E6ENGA06B01", "Desc": "도움 제안하고 답하기"},
    {"ID": "E6ENGA06B02", "Desc": "원하는 물건 말하기"},
    {"ID": "E6ENGA06B03", "Desc": "가격 묻고 답하기"},
    {"ID": "E6ENGA07B01", "Desc": "감정이나 상태 표현하기"},
    {"ID": "E6ENGA07B02", "Desc": "감정이나 상태의 이유 묻고 답하기"},
    {"ID": "E6ENGA07B03", "Desc": "몸 상태 묻고 답하기"},
    {"ID": "E6ENGA07B04", "Desc": "유감이나 위로 표현하기"},
    {"ID": "E6ENGA08B01", "Desc": "과거의 경험이나 사실 묻고 답하기"},
    {"ID": "E6ENGA08B02", "Desc": "미래의 계획 묻고 답하기"},
    {"ID": "E6ENGA09B01", "Desc": "전화 걸고 받기"},
    {"ID": "E6ENGA09B02", "Desc": "안부 묻고 답하기"},
    {"ID": "E6ENGA09B03", "Desc": "현재 행동 묻고 답하기"},
    {"ID": "E6ENGA09B04", "Desc": "원하는 활동 권유하기"},
    {"ID": "E6ENGA10B01", "Desc": "제안이나 권유하고 답하기"},
    {"ID": "E6ENGA10B02", "Desc": "허락 요청하고 답하기"},
    {"ID": "E6ENGA10B03", "Desc": "초대하고 답하기 "},
    {"ID": "E6ENGA11B01", "Desc": "다양한 문화에 대해 알고 있는지 묻고 답하기"},
    {"ID": "M3ENGA01B01", "Desc": "자기 소개하기"},
    {"ID": "M3ENGA01B02", "Desc": "학교생활 소개하기"},
    {"ID": "M3ENGA02B01", "Desc": "좋아하는 것 묻기,What do you like?,What is your favorite Korean food?,What color do you like?,Which do you prefer soccer or basketball?"},
    {"ID": "M3ENGA02B02", "Desc": "좋아하는 것 말하기,I like baseball.,My favorite subject is math.,I would like to play soccer.,This food is one of my favorite food.,I prefer Tteokbokki."},
    {"ID": "M3ENGA02B03", "Desc": "좋아하지 않는 것 말하기,I don't like to eat banana.,I hate to play badminton.,I don't like visiting Japan."},
    {"ID": "M3ENGA03B01", "Desc": "관심 및 원하는 것 묻기,What are you interested in?,What do you usually do in your free time?,What do you want to get for your birthday?"},
    {"ID": "M3ENGA03B02", "Desc": "관심 및 원하는 것 말하기,I'm interested in designing clothes.,I'm really into photos.,I enjoy listening to music.,I like to play baseball.,I want to get a new cell phone."},
    {"ID": "M3ENGA03B03", "Desc": "관심사 정보 나누기,I can give you some useful tips.,I had an interwiew with a famous chef, Jason."},
    {"ID": "M3ENGA04B01", "Desc": "인물의 외모 및 행동 묘사하기"},
    {"ID": "M3ENGA04B02", "Desc": "동물 및 사물의 특징 묘사하기,It has four legs.,Otters eat; rest; and sleep in the water.,The sides fit together and there is no space between them."},
    {"ID": "M3ENGA05B01", "Desc": "안부 묻기,How are you?,How are you doing?"},
    {"ID": "M3ENGA05B02", "Desc": "안부 말하기,Fine, thanks.,Great, thanks. And you?,Not bad, thanks."},
    {"ID": "M3ENGA05B03", "Desc": "제3자에게 안부 전하기,Say hello to him.,Give my regards to her.,Remember me to your mother."},
    {"ID": "M3ENGA06B01", "Desc": "축하/칭찬/격려하기,Congratulations!,Congratulations on winning the gold medal.,You did a good job.,Don't give up.,You can do it."},
    {"ID": "M3ENGA06B02", "Desc": "감사하기,Thank you.,I really appreciate your help.,How nice of you!"},
    {"ID": "M3ENGA07B01", "Desc": "감정 묻기,How do you feel?,What's up?"},
    {"ID": "M3ENGA07B02", "Desc": "감정 말하기"},
    {"ID": "M3ENGA08B01", "Desc": "의견 묻기,What do you think about math?,What do you think of this notebook?,How was the movie?"},
    {"ID": "M3ENGA08B02", "Desc": "의견 말하기,I think it's interesting.,I think it's boring.,It looks great!,It was fun."},
    {"ID": "M3ENGA08B03", "Desc": "동의 또는 반대하기,I think so.,I agree.,I don't think so.,I don't agree.,That's a good idea."},
    {"ID": "M3ENGA09B01", "Desc": "도움 요청하기,Can you please do the dishes?,Can you give me a hand?"},
    {"ID": "M3ENGA09B02", "Desc": "도움 요청에 답하기,Sure.,No problem.,I'm sorry, but I can't."},
    {"ID": "M3ENGA09B03", "Desc": "설명 요청하기,Can you explain how to return these books?,What does that mean?"},
    {"ID": "M3ENGA09B04", "Desc": "설명 요청에 응하기,Sure. First, insert the card. Then put the books in this box.,It means It's raining a lot."},
    {"ID": "M3ENGA09B05", "Desc": "알고 있는지 묻기,You know that they are in danger, don't you?,Have you heard about the magic show?"},
    {"ID": "M3ENGA09B06", "Desc": "알고 있음 표현하기,I heard it will rain tomorrow., I heard that many people were waiting for the trip."},
    {"ID": "M3ENGA10B01", "Desc": "허락 구하기,May/Can I come in?,Can/May I open the window?,Do you mind if I borrow your pen?"},
    {"ID": "M3ENGA10B02", "Desc": "수락/거절하기,Sure. Go ahead.,I'm sorry, I'm a little busy now.,Certainly not."},
    {"ID": "M3ENGA11B01", "Desc": "계획 묻기,What are you going to do this weekend?,What are you planning to do this weekend?,What is your plan for this winter vacation?,Do you have any special plans for this weekend?,What do you want to do this summer vacation?"},
    {"ID": "M3ENGA11B02", "Desc": "계획 말하기,I'm going to see a movie.,I'm thinking of studying English this weekend.,I'm planning to visit Jeju island."},
    {"ID": "M3ENGA12B01", "Desc": "길 묻고 답하기"},
    {"ID": "M3ENGA12B02", "Desc": "소요 시간 묻고 답하기"},
    {"ID": "M3ENGA13B01", "Desc": "약속 장소 묻고 답하기"},
    {"ID": "M3ENGA13B02", "Desc": "약속 시간 묻고 답하기"},
    {"ID": "M3ENGA14B01", "Desc": "대화 장소 파악하기,How can I help you?,I'm looking for the book; Chicken Soup for the Soul."},
    {"ID": "M3ENGA14B02", "Desc": "화자 간의 관계 파악하기,Why are you late for my class?,Sorry, ma'am. I got up late this morning."},
    {"ID": "M3ENGA15B01", "Desc": "물건 구매하기"},
    {"ID": "M3ENGA15B02", "Desc": "물건 판매하기"},
    {"ID": "M3ENGA15B03", "Desc": "물건 교환이나 환불 요청하기,I'd like to exchange this bag.,I'd like to get a refund for this bag."},
    {"ID": "M3ENGA16B01", "Desc": "이유 묻기,Why do you say that?,Why do you think so?,I'm curious about the reason.,I wonder why he was late."},
    {"ID": "M3ENGA16B02", "Desc": "이유 말하기,Because he is kind."},
    {"ID": "M3ENGA17B01", "Desc": "고민 묻고 답하기"},
    {"ID": "M3ENGA17B02", "Desc": "조언 묻고 답하기"},
    {"ID": "M3ENGA17B03", "Desc": "상태 묻고 위로하기"},
    {"ID": "M3ENGA18B01", "Desc": "경험 묻기,Have you ever had any Mexican food?"},
    {"ID": "M3ENGA18B02", "Desc": "경험 말하기,Yes, I've had it before.,Yes, I have.,No, I haven't.,No, I've never.,I have been to Korea three times."},
    {"ID": "M3ENGA19B01", "Desc": "과거 사실 묻기,What did you do yesterday?,Did you play badminton?"},
    {"ID": "M3ENGA19B02", "Desc": "과거 사실 말하기,I took pictures in the park.,Yes, I did.,No, I didn't. I played soccer."},
    {"ID": "M3ENGA20B01", "Desc": "도표 읽기,Bongo is older than Bada.,John is the tallest boy in his class."},
    {"ID": "M3ENGA20B02", "Desc": "그림 또는 사진 묘사하기,There is a cat under the table.,In picture A, there are three books on the chair."},
    {"ID": "M3ENGA21B01", "Desc": "관용어구 활용하기,sleep tight,a piece of cake,It's raining cats and dogs.,Break a leg.,I feel under the weather."},
    {"ID": "M3ENGA21B02", "Desc": "속담 활용하기,Early bird gets the worm."},
    {"ID": "M3ENGA21B03", "Desc": "명언 활용하기,What is essential is invisible to the eye.,Stay hungry, stay foolish."},
    {"ID": "H1ENGA01B01", "Desc": "자기 소개하기"},
    {"ID": "H1ENGA01B02", "Desc": "인물 소개하기"},
    {"ID": "H1ENGA02B01", "Desc": "정보 유무 확인하기"},
    {"ID": "H1ENGA02B02", "Desc": "정보 요청하기"},
    {"ID": "H1ENGA02B03", "Desc": "정보 표현하기"},
    {"ID": "H1ENGA02B04", "Desc": "정보 이해하기"},
    {"ID": "H1ENGA03B01", "Desc": "의견 요청하기"},
    {"ID": "H1ENGA03B02", "Desc": "의견 표현하기"},
    {"ID": "H1ENGA03B03", "Desc": "의견 이해하기"},
    {"ID": "H1ENGA04B01", "Desc": "시각 자료를 활용하여 설명하기"},
    {"ID": "H1ENGA04B02", "Desc": "시각 자료에 대한 설명 이해하기"},
    {"ID": "H1ENGA05B01", "Desc": "감정 묻기"},
    {"ID": "H1ENGA05B02", "Desc": "긍정적 감정 표현하기"},
    {"ID": "H1ENGA05B03", "Desc": "부정적 감정 표현하기"},
    {"ID": "H1ENGA05B04", "Desc": "감정 이해하기"},
    {"ID": "H1ENGA06B01", "Desc": "경험 묻기"},
    {"ID": "H1ENGA06B02", "Desc": "경험 표현하기"},
    {"ID": "H1ENGA07B01", "Desc": "바람이나 계획 묻기"},
    {"ID": "H1ENGA07B02", "Desc": "바람이나 계획 표현하기"},
    {"ID": "H1ENGA08B01", "Desc": "도움 요청하기"},
    {"ID": "H1ENGA08B02", "Desc": "도움 제안하기"},
    {"ID": "H1ENGA08B03", "Desc": "조언 요청하기"},
    {"ID": "H1ENGA08B04", "Desc": "조언 표현하기"},
    {"ID": "H1ENGA09B01", "Desc": "대화 상황 파악하기"},
    {"ID": "H1ENGA09B02", "Desc": "글의 특성 파악하기"},
    {"ID": "H1ENGA09B03", "Desc": "함축적 의미 이해하기"},
    {"ID": "E4ENGA01B01C01", "Desc": "아침,점심,저녁 인사하기,Good morning?,Good morning.,Good afternoon?,Good afternoon.,Good evening?,Good evening."},
    {"ID": "E4ENGA01B02C02", "Desc": "안부 묻기,How are you?"},
    {"ID": "E4ENGA01B02C03", "Desc": "안부를 묻는 말에 답하기,I am great."},
    {"ID": "E4ENGA02B01C01", "Desc": "이름 묻기,What is your name?"},
    {"ID": "E4ENGA02B01C02", "Desc": "이름 말하기,My name is Jina."},
    {"ID": "E4ENGA02B01C03", "Desc": "좋아하는 것 묻기,Do you like apples?"},
    {"ID": "E4ENGA02B01C04", "Desc": "좋아하는 것을 묻는 말에 답하기,Yes I do.,No I don't."},
    {"ID": "E4ENGA02B01C05", "Desc": "좋아하는 것 말하기,I like pizza."},
    {"ID": "E4ENGA02B01C06", "Desc": "직업 묻기,What do you do?,What does he/she do?,"},
    {"ID": "E4ENGA02B01C07", "Desc": "직업을 묻는 말에 답하기,I am a doctor."},
    {"ID": "E4ENGA02B02C08", "Desc": "누구인지 묻기,Who is he/she?"},
    {"ID": "E4ENGA02B02C09", "Desc": "누구인지 묻는 말에 답하기,He is my father."},
    {"ID": "E4ENGA02B02C10", "Desc": "인물 묘사하기,He is tall."},
    {"ID": "E4ENGA02B02C11", "Desc": "친구나 가족 소개하기,This is my father."},
    {"ID": "E4ENGA02B02C12", "Desc": "처음 만났을 때 하는 인사 나누기,Nice to meet you.,Nice to meet you too."},
    {"ID": "E4ENGA02B02C13", "Desc": "나이 묻기,How old are you?"},
    {"ID": "E4ENGA02B02C14", "Desc": "나이를 묻는 말에 답하기,I'm seven years old."},
    {"ID": "E4ENGA03B01C01", "Desc": "감정 묻기,Are you happy?"},
    {"ID": "E4ENGA03B01C02", "Desc": "감정을 묻는 말에 답하기,Yes I am.,No I'm not."},
    {"ID": "E4ENGA03B01C03", "Desc": "감정 표현하기,I'm happy."},
    {"ID": "E4ENGA03B02C04", "Desc": "상태 묻기,Are you hungry?"},
    {"ID": "E4ENGA03B02C05", "Desc": "상태를 묻는 말에 답하기,Yes I am.,No I'm not."},
    {"ID": "E4ENGA03B02C06", "Desc": "상태 표현하기,I'm hungry."},
    {"ID": "E4ENGA04B01C01", "Desc": "날씨 묻기,How's the weather?"},
    {"ID": "E4ENGA04B01C02", "Desc": "날씨를 묻는 말에 답하기,It's sunny."},
    {"ID": "E4ENGA05B01C01", "Desc": "원하는 개수 묻기,How many carrots?"},
    {"ID": "E4ENGA05B01C02", "Desc": "원하는 개수를 묻는 말에 답하기,Two carrots."},
    {"ID": "E4ENGA06B01C01", "Desc": "능력 묻기,Can you swim?"},
    {"ID": "E4ENGA06B01C02", "Desc": "능력 묻는 말에 답하기,Yes I can.,No I can't."},
    {"ID": "E4ENGA06B02C03", "Desc": "할 수 있는 것 말하기,I can swim."},
    {"ID": "E4ENGA06B03C04", "Desc": "할 수 없는 것 말하기,I can't skate."},
    {"ID": "E4ENGA07B01C01", "Desc": "시각 묻기,What time is it?"},
    {"ID": "E4ENGA07B01C02", "Desc": "시각을 묻는 말에 답하기,It's eight o'clock.,It's eight thirty."},
    {"ID": "E4ENGA07B01C03", "Desc": "일과 말하기,It's time for lunch."},
    {"ID": "E4ENGA07B02C04", "Desc": "요일 묻기,What day is it?"},
    {"ID": "E4ENGA07B02C05", "Desc": "요일을 묻는 말에 답하기,It's Friday."},
    {"ID": "E4ENGA07B02C06", "Desc": "요일별 활동 말하기,I/We have a cooking class."},
    {"ID": "E4ENGA07B02C07", "Desc": "(요일별 활동에 대한) 의견 말하기,That's great."},
    {"ID": "E4ENGA08B01C01", "Desc": "물건의 주인 묻기,Is this your bag?"},
    {"ID": "E4ENGA08B01C02", "Desc": "물건의 주인을 묻는 말에 답하기,Yes it is.,No it isn't."},
    {"ID": "E4ENGA08B01C03", "Desc": "물건 묘사하기,My shoe is pink."},
    {"ID": "E4ENGA08B02C04", "Desc": "물건을 가지고 있는지 묻기Do you have a ball?"},
    {"ID": "E4ENGA08B02C05", "Desc": "물건을 가지고 있는지 묻는 말에 답하기Yes I do.,No I don't."},
    {"ID": "E4ENGA09B01C01", "Desc": "물건의 위치 묻기,Where is my bag?"},
    {"ID": "E4ENGA09B01C02", "Desc": "물건의 위치를 묻는 말에 답하기,It's on the desk.,I don't know."},
    {"ID": "E4ENGA09B02C03", "Desc": "(잃어버린 사람에게) 위로 표현하기,Don't worry."},
    {"ID": "E4ENGA09B03C04", "Desc": "(찾아준 사람에게) 감사 표현하기,Thank you."},
    {"ID": "E4ENGA09B03C05", "Desc": "(찾아준 사람에게) 감사를 표현하는 말에 답하기,You're welcome."},
    {"ID": "E4ENGA10B01C01", "Desc": "제안하기,Let's play soccer."},
    {"ID": "E4ENGA10B01C02", "Desc": "제안하는 말에 답하기,Okay.,Sounds great!,Sorry I can't."},
    {"ID": "E4ENGA10B01C03", "Desc": "제안의 거절 이유 말하기,I am tired.,I have homework.,Don't worry."},
    {"ID": "E4ENGA10B02C04", "Desc": "음식 권유하기,Do you want some water?"},
    {"ID": "E4ENGA10B02C05", "Desc": "음식을 권유하는 말에 답하기,Yes please.,No, thanks."},
    {"ID": "E4ENGA10B02C06", "Desc": "권유의 거절 이유 말하기,I am full."},
    {"ID": "E4ENGA10B03C07", "Desc": "지시하는 말하기,Line up.,Pick up the trash.,Touch your feet.,Put the bottle here."},
    {"ID": "E4ENGA10B04C08", "Desc": "금지하는 말하기,Don't run, please."},
    {"ID": "E4ENGA11B01C01", "Desc": "원하는 물건 묻기,What do you want?"},
    {"ID": "E4ENGA11B01C02", "Desc": "원하는 물건을 묻는 말에 답하기,I want this skirt."},
    {"ID": "E4ENGA11B02C03", "Desc": "물건의 이름 묻기,What's this/that?"},
    {"ID": "E4ENGA11B02C04", "Desc": "물건의 이름을 묻는 말에 답하기,It's a book."},
    {"ID": "E4ENGA11B03C05", "Desc": "가격 묻기,How much is it?"},
    {"ID": "E4ENGA11B03C06", "Desc": "가격을 묻는 말에 답하기,It is two hundred won."},
    {"ID": "E4ENGA11B03C07", "Desc": "가격에 대한 의견 말하기,It's cheap."},
    {"ID": "E4ENGA12B01C01", "Desc": "현재의 행동 묻기,What are you doing?,What is he/she doing?"},
    {"ID": "E4ENGA12B01C02", "Desc": "현재의 행동을 묻는 말에 답하기,I am cleaning.,He/She is cooking."},
    {"ID": "E4ENGA12B01C03", "Desc": "행동을 하고 있는 장소 말하기,I am in the kitchen."},
    {"ID": "E4ENGA12B02C04", "Desc": "도움 요청하기,Can you help me?"},
    {"ID": "E4ENGA12B02C05", "Desc": "도움을 요청하는 말에 답하기,Sure./Sure I can.,Sorry I can't."},
    {"ID": "E4ENGA12B03C06", "Desc": "허락 요청하기,Can I sit here?"},
    {"ID": "E4ENGA12B03C07", "Desc": "허락을 요청하는 말에 답하기,Sure.,Sorry you can't."},
    {"ID": "E6ENGA01B01C01", "Desc": "출신지 묻기,Where are you from?,Where is he/she from?"},
    {"ID": "E6ENGA01B01C02", "Desc": "출신지를 묻는 말에 답하기,I’m from Korea.,He/She's from India."},
    {"ID": "E6ENGA01B02C03", "Desc": "가장 좋아하는 계절 묻기,What’s your favorite season?"},
    {"ID": "E6ENGA01B02C04", "Desc": "가장 좋아하는 계절을 묻는 말에 답하기,My favorite season is summer."},
    {"ID": "E6ENGA01B02C05", "Desc": "좋아하는 과목 묻기,What subject do you like?,What's your favorite subject?"},
    {"ID": "E6ENGA01B02C06", "Desc": "좋아하는 과목을 묻는 말에 답하기,I like science.My favorite subject is science."},
    {"ID": "E6ENGA01B02C07", "Desc": "좋아하는 활동 묻기,What do you like?,Do you like singing?"},
    {"ID": "E6ENGA01B02C08", "Desc": "좋아하는 활동을 묻는 말에 답하기,I like watching the moon.,Yes, I do.,No, I don’t."},
    {"ID": "E6ENGA01B02C09", "Desc": "(활동에 대한) 칭찬하기,Excellent!,Good job!,Great!"},
    {"ID": "E6ENGA01B03C10", "Desc": "장래희망 묻기,What do you want to be?"},
    {"ID": "E6ENGA01B03C11", "Desc": "장래희망을 묻는 말에 답하기,I want to be an artist."},
    {"ID": "E6ENGA01B03C12", "Desc": "(장래희망과 관련된) 잘하는 것 말하기,I am good at painting."},
    {"ID": "E6ENGA01B03C13", "Desc": "(장래희망과 관련된) 좋아하는 것 말하기,I like to paint.,I love painting."},
    {"ID": "E6ENGA01B04C14", "Desc": "학년 묻기What grade are you in?"},
    {"ID": "E6ENGA01B04C15", "Desc": "학년을 묻는 말에 답하기,I am in the sixth grade."},
    {"ID": "E6ENGA01B05C16", "Desc": "이름 철자 묻기,How do you spell your name?"},
    {"ID": "E6ENGA01B05C17", "Desc": "이름 철자를 묻는 말에 답하기,J-A-S-O-N."},
    {"ID": "E6ENGA02B01C01", "Desc": "외모 묻기,What does he/she look like?"},
    {"ID": "E6ENGA02B01C02", "Desc": "외모를 묻는 말에 답하기,He/She is tall.,He/She looks like a model."},
    {"ID": "E6ENGA02B01C03", "Desc": "신체 특징 묘사하기,He/She has curly hair."},
    {"ID": "E6ENGA02B01C04", "Desc": "옷차림 묘사하기,He/She is wearing a blue shirt."},
    {"ID": "E6ENGA02B01C05", "Desc": "키 묻기,How tall are you?"},
    {"ID": "E6ENGA02B01C06", "Desc": "키를 묻는 말에 답하기,I am 150 centimenters tall."},
    {"ID": "E6ENGA02B02C07", "Desc": "다른 사람의 특징 설명하기,He/She runs fast."},
    {"ID": "E6ENGA02B03C08", "Desc": "두 대상을 비교하여 묻기,Who/What is stronger, A or B?"},
    {"ID": "E6ENGA02B03C09", "Desc": "두 대상을 비교하여 묻는 말에 답하기,A is stronger than B."},
    {"ID": "E6ENGA02B03C10", "Desc": "(두 대상을 비교하는 표현에) 의견 말하기,I think/don't think so.,That's not right."},
    {"ID": "E6ENGA03B01C01", "Desc": "물어볼 상대에게 말 걸기,Excuse me."},
    {"ID": "E6ENGA03B02C02", "Desc": "길 묻기,Where is the museum?"},
    {"ID": "E6ENGA03B02C03", "Desc": "길을 묻는 말에 답하기,Go straight two blocks.,Turn right/left.,It is behind the bank.,It is on your right/left.,It is on the first floor."},
    {"ID": "E6ENGA03B03C04", "Desc": "찾아가는 방법 묻기,How can I get to the Wedding House?"},
    {"ID": "E6ENGA03B03C05", "Desc": "찾아가는 방법을 묻는 말에 답하기,Take bus Number 7 and get off at the Green Market."},
    {"ID": "E6ENGA03B03C06", "Desc": "(찾아가는 방법) 되묻기,Pardon?,Pardon me?,Sorry?,Excuse me?"},
    {"ID": "E6ENGA03B03C07", "Desc": "(찾아가는 방법에 대한) 확실성 표현하기,You can't miss it."},
    {"ID": "E6ENGA04B01C01", "Desc": "일과 묻기,What time do you get up?"},
    {"ID": "E6ENGA04B01C02", "Desc": "일과를 묻는 말에 답하기,I get up at 6:00."},
    {"ID": "E6ENGA04B01C03", "Desc": "(일과에 대한) 의견 말하기,That’s very early."},
    {"ID": "E6ENGA04B02C04", "Desc": "오늘 날짜 묻기,What is the date today?"},
    {"ID": "E6ENGA04B02C05", "Desc": "오늘 날짜를 묻는 말에 답하기,It is January first/1st."},
    {"ID": "E6ENGA04B03C06", "Desc": "생일 묻기,When is your birthday?"},
    {"ID": "E6ENGA04B03C07", "Desc": "생일을 묻는 말에 답하기,It is January first/1st."},
    {"ID": "E6ENGA04B03C08", "Desc": "특정일 묻기,When is Earth Day?"},
    {"ID": "E6ENGA04B03C09", "Desc": "특정일을 묻는 말에 답하기,It is April twenty second/22nd."},
    {"ID": "E6ENGA04B03C10", "Desc": "(특정일에 대한) 기대 표현하기,I can't wait."},
    {"ID": "E6ENGA05B01C01", "Desc": "물건의 주인 묻기,Whose ball is this/it?,Whose gloves are these?"},
    {"ID": "E6ENGA05B01C02", "Desc": "물건의 주인을 묻는 말에 답하기,It’s mine.It’s not mine.,It’s Peter’s.,They’re mine."},
    {"ID": "E6ENGA05B02C03", "Desc": "(찾아준 사람에게) 감사 표현하기,Thanks a lot."},
    {"ID": "E6ENGA06B01C01", "Desc": "도움 제안하기,May I help you?,Can I help you?"},
    {"ID": "E6ENGA06B01C02", "Desc": "도움을 제안하는 말에 답하기,Yes, please."},
    {"ID": "E6ENGA06B02C03", "Desc": "구입하려는 물건 말하기,I’m looking for a kite.,I want an umbrella.,I want glasses."},
    {"ID": "E6ENGA06B02C04", "Desc": "구매의사 표현하기,I’ll take it.,I’ll take them."},
    {"ID": "E6ENGA06B03C05", "Desc": "가격 묻기,How much is it?,How much are these/they?"},
    {"ID": "E6ENGA06B03C06", "Desc": "가격을 묻는 말에 답하기,It’s 10 dollars.,They are 6 dollars."},
    {"ID": "E6ENGA06B03C07", "Desc": "(가격에 대한) 의견 말하기,It's too expensive.,They're expensive.,It's cheap."},
    {"ID": "E6ENGA07B01C01", "Desc": "자신의 감정이나 상태 표현하기,I am sad.,I feel happy."},
    {"ID": "E6ENGA07B01C02", "Desc": "다른 사람의 감정이나 상태 표현하기,You look busy."},
    {"ID": "E6ENGA07B02C03", "Desc": "감정이나 상태의 이유 묻기,Why are you upset?"},
    {"ID": "E6ENGA07B02C04", "Desc": "감정이나 상태의 이유를 묻는 말에 답하기,Because my brother broke my glasses."},
    {"ID": "E6ENGA07B03C05", "Desc": "몸 상태 묻기,What's wrong?,What's the problem?,What's the matter?,Are you okay?"},
    {"ID": "E6ENGA07B03C06", "Desc": "몸 상태를 묻는 말에 답하기,I have a headache."},
    {"ID": "E6ENGA07B04C07", "Desc": "유감이나 위로를 표현하는 말하기,That's too bad.,I'm sorry.,Don't worry.,Cheer up."},
    {"ID": "E6ENGA07B04C08", "Desc": "(건강에 관련된) 조언하기,(You should) get some rest."},
    {"ID": "E6ENGA08B01C01", "Desc": "과거의 경험 묻기,What did you do?,Did you go there?"},
    {"ID": "E6ENGA08B01C02", "Desc": "과거의 경험을 묻는 말에 답하기,I went to the park.,Yes, I did.,No, I didn't."},
    {"ID": "E6ENGA08B01C03", "Desc": "과거의 사실 묻기,Who invented Hangul?"},
    {"ID": "E6ENGA08B01C04", "Desc": "과거의 사실을 묻는 말에 답하기,King Sejong did."},
    {"ID": "E6ENGA08B02C05", "Desc": "미래의 계획 묻기,What will you do during the vacation?,What are you going to do?"},
    {"ID": "E6ENGA08B02C06", "Desc": "미래의 계획을 묻는 말에 답하기,I will learn French.,I am going to visit my uncle."},
    {"ID": "E6ENGA08B02C07", "Desc": "미래의 계획에 대한 의견 말하기,That's a good idea.,Sounds great.,That sounds fun.,What a nice plan!,That's nice."},
    {"ID": "E6ENGA08B02C08", "Desc": "교통수단에 관한 계획 묻기,How will you get there?"},
    {"ID": "E6ENGA08B02C09", "Desc": "교통수단에 관한 계획을 묻는 말에 답하기,I will get there by plane."},
    {"ID": "E6ENGA09B01C01", "Desc": "전화 걸기,Hello.,This is Yuna.,May/Can I speak to Minho?,Is Minho there?"},
    {"ID": "E6ENGA09B01C02", "Desc": "전화 받기,Hello.,Speaking.,Hold on please.,Who's calling please?,Who's this?It's Minho."},
    {"ID": "E6ENGA09B02C03", "Desc": "How are you?,How's it going?, How about you?"},
    {"ID": "E6ENGA09B02C04", "Desc": "I'm fine/great.,Fine, thanks.,Not bad."},
    {"ID": "E6ENGA09B03C05", "Desc": "(전화 상대에게) 현재 행동 묻기,What are you doing?"},
    {"ID": "E6ENGA09B03C06", "Desc": "(전화 상대에게) 현재 행동을 묻는 말에 답하기,We are playing a board game."},
    {"ID": "E6ENGA09B04C07", "Desc": "(전화 상대에게) 원하는 활동 말하고 권유하기,I want to play soccer.,Let's meet at 2:30.,Let's meet at the park."},
    {"ID": "E6ENGA10B01C01", "Desc": "제안하기,Would you like to watch a movie?,Let's have a pajama party.,Can you join me?"},
    {"ID": "E6ENGA10B01C02", "Desc": "제안하는 말에 답하기,Of course.,Sounds great.,I’d love to, but I can’t.,No problem.,Sorry, I can’t."},
    {"ID": "E6ENGA10B01C03", "Desc": "음식 권유하기,Help yourself.,Please try some.,Please go ahead.,Do you want some more?"},
    {"ID": "E6ENGA10B01C04", "Desc": "음식을 권유하는 말에 답하기,Yes, please.,No, thanks. I'm full."},
    {"ID": "E6ENGA10B01C05", "Desc": "거절에 응답하기,That’s all right.,Maybe next time."},
    {"ID": "E6ENGA10B02C06", "Desc": "허락 요청하기,May I take pictures here?,Can I sit here?"},
    {"ID": "E6ENGA10B02C07", "Desc": "허락을 요청하는 말에 답하기,Yes, you may.,Sure.,Sorry, you can’t."},
    {"ID": "E6ENGA10B03C08", "Desc": "초대하기,Can you come to our magic show?"},
    {"ID": "E6ENGA10B03C09", "Desc": "초대하는 말에 답하기,All right.,Of course.,Sorry, but I have a guitar lesson.,Sorry, I can't."},
    {"ID": "E6ENGA11B01C01", "Desc": "다양한 문화에 대해 알고 있는지 묻기,Do you konw anything about Hanok?"},
    {"ID": "E6ENGA11B01C02", "Desc": "다양한 문화에 대해 알고 있는지 묻는 말에 답하기,Yes, I do.,Yes, I know about it.,No, I don't.,No, I have no idea."},
    {"ID": "E6ENGA11B01C03", "Desc": "표현 되묻기,What did you say?"},
    {"ID": "E6ENGA11B01C04", "Desc": "표현을 되묻는 말에 답하기,I said Hanok."},
    {"ID": "M3ENGA01B01C01", "Desc": "기본정보 말하기,Let me introduce myself.,My name is Mira.,I'm from Korea.,I'm 14 years old.,I go to Boram middle school.,This is my family.,My dad is a teacher."},
    {"ID": "M3ENGA01B01C02", "Desc": "성격 말하기,I am active; optimistic; and diligent.,I am very shy and quiet."},
    {"ID": "M3ENGA01B01C03", "Desc": "관심사/취미/잘하는 것 소개하기,I'm good at cooking.,I'm interested in drawing pictures.,I enjoy listening to music.,I'm good at folding paper."},
    {"ID": "M3ENGA01B01C04", "Desc": "장래 희망/버킷리스트 소개하기,In the future; I will be a famous singer.,I want to be a famous singer.,I'd like to travel around the world."},
    {"ID": "M3ENGA01B02C05", "Desc": "교과 및 동아리 활동 ,My favorite subject is English.,I like English the best.,I want to join the photo class.,Because I love to take photos."},
    {"ID": "M3ENGA01B02C06", "Desc": "학교 규칙,You should bring your textbook.,Don't run in the classroom."},
    {"ID": "M3ENGA04B01C01", "Desc": "인물의 외모 및 동작 묻기, What does she look like?,What is he doing?"},
    {"ID": "M3ENGA04B01C02", "Desc": "인물의 외모 및 동작 말하기,She is tall and slim.,He is much taller than his brother.,She is wearing a cap.,He is dancing."},
    {"ID": "M3ENGA07B02C01", "Desc": "아쉬움이나 후회 표현하기,I should have studied harder."},
    {"ID": "M3ENGA07B02C02", "Desc": "미안함 표현하기/사과하기,I'm so sorry.,Will you accept my apology?"},
    {"ID": "M3ENGA07B02C03", "Desc": "기쁨 표현하기,Glad to hear that.,That's great!,I feel happy/glad/delighted."},
    {"ID": "M3ENGA07B02C04", "Desc": "화남 표현하기,I'm so mad at you.,I'm angry.,I'm so upset."},
    {"ID": "M3ENGA07B02C05", "Desc": "실망 표현하기,I'm so disappointed at you."},
    {"ID": "M3ENGA12B01C01", "Desc": "길 묻기,Where is the school?,How do I get to the City Hall?,Where can I find women's clothes?"},
    {"ID": "M3ENGA12B01C02", "Desc": "길 묻기에 대한 답하기,It's on Green Street.,Go straight one block and turn left.,It's across from the hospital.,You'll find it."},
    {"ID": "M3ENGA12B01C03", "Desc": "교통 수단 말하기,How do you go to City Hall?,How do I get there?,You go to the City Hall by subway.,I ride my bike to the City Hall."},
    {"ID": "M3ENGA12B02C04", "Desc": "소요 시간 묻기,How long does it take to go to City Hall?"},
    {"ID": "M3ENGA12B02C05", "Desc": "소요 시간 답하기,It takes about 25 minutes by bus."},
    {"ID": "M3ENGA13B01C01", "Desc": "약속 장소 묻기,Where should we meet?,Where shall we meet?,Where can I meet you?,Where would be good for you?,Where can you make it?"},
    {"ID": "M3ENGA13B01C02", "Desc": "약속 장소 제안하기,Let's meet at the ballpark.,I would like to meet at school gate."},
    {"ID": "M3ENGA13B01C03", "Desc": "약속 승낙 또는 거절하기,Okay, I will be there at two.,That will be fine.,Sure, I'll see you at the school.,Sounds great!,Let's go there together.,Sorry, I have to do my homework this Saturday."},
    {"ID": "M3ENGA13B02C04", "Desc": "약속 시간 묻기,What time should we meet?,When do you want to meet?,What time is convenient for you?,What time would you like to meet?"},
    {"ID": "M3ENGA13B02C05", "Desc": "약속 시간 말하기,Let's meet at four o'clock.,How about next Saturday?"},
    {"ID": "M3ENGA15B01C01", "Desc": "사고 싶은 물건 말하기,I'm looking for a shirt.,I want to buy some cake.,I would like to buy this book.,Do you have a yellow shirt?"},
    {"ID": "M3ENGA15B01C02", "Desc": "가격 알아보기,How much is it?,How much is these gloves?,How much does it cost?,They are 40 dollars.,It is 40 dollars."},
    {"ID": "M3ENGA15B01C03", "Desc": "물건 구매 수락 또는 거절하기,Okay, I'll take them.,Sounds great!,That's too expensive. Can I get a discount?,Could you show me another one?"},
    {"ID": "M3ENGA15B02C04", "Desc": "손님 맞이하기,May I help you?,Can I help you?,Anything can I help you?,What can I do for you?"},
    {"ID": "M3ENGA15B02C05", "Desc": "물건 제안하기,How about these shoes?,Do you like this shirt?,What do you think of this shirt?"},
    {"ID": "M3ENGA17B01C01", "Desc": "고민 묻기,What's up?,What's wrong with you?,What's the mattter?,Are you all right?,What's your problem?"},
    {"ID": "M3ENGA17B01C02", "Desc": "고민 말하기,고민하는 글쓰기,I had argument with my classmate.,I am really mad at my friend.,I really want to be diligent but I can't.,I would like to speak English well but I can't.,My best friend will move to another school."},
    {"ID": "M3ENGA17B02C03", "Desc": "조언 요청하기,조언을 요청하는 글쓰기,Can you give me some advice?,I don't know what I should do."},
    {"ID": "M3ENGA17B02C04", "Desc": "조언하기,조언하는 글쓰기,Why don't you study English?,How about going to go a movie theater?,You should call your mother.,You need to bring your textbook."},
    {"ID": "M3ENGA17B03C05", "Desc": "상태 묻기,What's wrong?,Do you have any problem?,Is there anything I can do to help you?"},
    {"ID": "M3ENGA17B03C06", "Desc": "위로하기,It's not so bad.,You must give it time.,I can't believe it.,I'm so sorry.,Just remember that you have me.,Don't be disappointed.,Cheer up!,Things will be better.,Everything is gonna be okay.,Don't worry. Be happy."},
    {"ID": "H1ENGA01B01C01", "Desc": "잘할 수 있는 것 소개하기,I'm good at English."},
    {"ID": "H1ENGA01B01C02", "Desc": "관심 분야 소개하기,What are you interested in?,I  enjoy singing."},
    {"ID": "H1ENGA01B01C03", "Desc": "장래 희망 소개하기,My dream job would be to work in scientific research."},
    {"ID": "H1ENGA01B02C04", "Desc": "기본 정보 소개하기,I'd like to introduce my friend, Tony Jackson.,His nickname is Smiley.,His hobby is playing sports.,She was born in August 26, 1910."},
    {"ID": "H1ENGA01B02C05", "Desc": "업적 소개하기,She became the first female pilot."},
    {"ID": "H1ENGA02B01C01", "Desc": "알고 있는지 묻기,Have you heard about a 3D printer?,Do you know what the most popular sport in India is?"},
    {"ID": "H1ENGA02B02C02", "Desc": "궁금증 표현하기,I wonder what I can make with it.,Can you tell me about the invention?,I'd be interested to know how it works."},
    {"ID": "H1ENGA02B02C03", "Desc": "설명 요청하기,What do you mean by that?,Can you explain the reason for that?,What else do you know?"},
    {"ID": "H1ENGA02B03C04", "Desc": "실생활 정보 표현하기,I'm writing this email in order to say sorry to you.,This is how you make tomato spaghetti.,Join a cultural event!"},
    {"ID": "H1ENGA02B03C05", "Desc": "지식 정보 표현하기,This kind of painting is called minhwa in Korean., Enormous ice sheets are melting away.,You cannot hear any sound in outer space."},
    {"ID": "H1ENGA02B04C06", "Desc": "실생활 정보 이해하기,According to the recipe, we should boil it for five minutes.,The notice say that the festival will be held next month."},
    {"ID": "H1ENGA02B04C07", "Desc": "지식 정보 이해하기,This writing is about the bad side of acid in sodas.The paragraph shows how deforestation is serious."},
    {"ID": "H1ENGA03B01C01", "Desc": "의견 묻기,What do you think of keeping animals in zoos?"},
    {"ID": "H1ENGA03B01C02", "Desc": "동의 여부 묻기,Do you agree with this plan?,Do you think this is a good idea?"},
    {"ID": "H1ENGA03B02C03", "Desc": "제안하기,I think you should consider their age.,Why don't you donate your clothes?"},
    {"ID": "H1ENGA03B02C04", "Desc": "의견 제시하기,I think it's important not to be stressed out.,It seems that the artists breathed new life into this area."},
    {"ID": "H1ENGA03B02C05", "Desc": "당부하기,Make sure we keep our environment clean.,Don't forget to bring the camera."},
    {"ID": "H1ENGA03B02C06", "Desc": "가능성 정도 표현하기,Maybe that will make it easier to fit in small places.,It's likely that you'll be able to find it everywhere in the future."},
    {"ID": "H1ENGA03B02C07", "Desc": "동의 여부 표현하기,I completely agree with you.,I'm with you.,I couldn't agree with you more.,I'm afraid, but I have to disagree on this matter."},
    {"ID": "H1ENGA03B02C08", "Desc": "의무 표현하기,We should be more interested in our town.,You're supposed to lower your voice in public places."},
    {"ID": "H1ENGA03B03C09", "Desc": "의견 파악하기,The writer argues that social media is very useful."},
    {"ID": "H1ENGA03B03C10", "Desc": "근거 파악하기,There are two reasons to support this opinion."},
    {"ID": "H1ENGA04B01C01", "Desc": "그림이나 사진을 활용하여 설명하기,There is a clock hung on the wall in the picture."},
    {"ID": "H1ENGA04B01C02", "Desc": "도표를 활용하여 설명하기,This graph shows what energy sources the world depends on.,The graph suggests that online shopping malls seem to have improved their payment."},
    {"ID": "H1ENGA04B02C03", "Desc": "그림이나 사진에 대한 설명 이해하기,The bookshelf under the clock is full of books in the picture."},
    {"ID": "H1ENGA04B02C04", "Desc": "도표에 대한 설명 이해하기,According to the graph, the largest amount of energy is oil.,The biggest change occurred in delivery, which decreased from 37.5% in 2014 to 16% in 2015."},
    {"ID": "H1ENGA05B01C01", "Desc": "감정 상태 묻기,How are you feeling today?,Is everything okay?,Are you feeling alright?,What's wrong?"},
    {"ID": "H1ENGA05B01C02", "Desc": "만족 여부 묻기,How do you like your new school?,Are you satisfied with the program?"},
    {"ID": "H1ENGA05B02C03", "Desc": "기쁨 표현하기,I'm delighted to hear that you liked it.,I'm glad that I had the opportunity to meet such amazing people."},
    {"ID": "H1ENGA05B02C04", "Desc": "놀람 표현하기,That's surprising!,I'm surprised that he memorized all the lines.,I was impressed with the food delivery service."},
    {"ID": "H1ENGA05B02C05", "Desc": "만족 표현하기,I'm happy with it.,I'm satisfied with it."},
    {"ID": "H1ENGA05B02C06", "Desc": "기대 표현하기,I'm looking forward to my first visit to Tokyo.,I can't wait to go there."},
    {"ID": "H1ENGA05B03C07", "Desc": "걱정 표현하기,I'm worried that it will get worse.,I'm worried about making mistakes.,I'm scared that I can't do it."},
    {"ID": "H1ENGA05B03C08", "Desc": "당혹감 표현하기,I'm confused right now.,I'm feeling overwhelmed.,I was frustrated by the questions."},
    {"ID": "H1ENGA05B03C09", "Desc": "불만족 표현하기,I'm not happy about it.,I'm not satisfied with it"},
    {"ID": "H1ENGA05B03C10", "Desc": "유감 표현하기,I'm sorry to hear that.,What a shame!"},
    {"ID": "H1ENGA05B04C11", "Desc": "심정 파악하기,It appears that they are feeling angry.,She seems to feel disappointed in the given context."},
    {"ID": "H1ENGA05B04C12", "Desc": "공감하기,I totally understand how you feel.,I can imagine how difficult that must be for you."},
    {"ID": "H1ENGA06B01C01", "Desc": "경험 여부 묻기,Have you ever been to the city?,Have you ever seen the sunrise?,Have you ever tried it before?"},
    {"ID": "H1ENGA06B01C02", "Desc": "소감 묻기,How was the trip?,How did you feel about the city?,Can you share your thoughts on the movie?"},
    {"ID": "H1ENGA06B02C03", "Desc": "경험한 사실 표현하기,I've been to the city.,I've seen the sunrise.,I've tried that before.,I visited the island last Saturday."},
    {"ID": "H1ENGA06B02C04", "Desc": "소감 표현하기,It was fun and refreshing.,It was unforgettable.,It was an amazing experience."},
    {"ID": "H1ENGA07B01C01", "Desc": "바람 묻기,What do you want to do?,What do you hope to achieve this year?"},
    {"ID": "H1ENGA07B01C02", "Desc": "계획 묻기,What are your plans for the new project?,Are there any specific plans you have for the trip?,What are you planning to do this weekend?"},
    {"ID": "H1ENGA07B02C03", "Desc": "바람 표현하기,I wish I could do more to help them.,My wish is to make a positive impact on the lives of others.,I hope to travel the world."},
    {"ID": "H1ENGA07B02C04", "Desc": "계획 표현하기,I'm planning to learn to play the guitar.,I'm thinking of going to the movies."},
    {"ID": "H1ENGA08B01C01", "Desc": "방법 묻기,Can you show me how to use this machine?"},
    {"ID": "H1ENGA08B01C02", "Desc": "부탁하기,May I ask you a favor?,Can you do me a favor?,Can you help me with this?Could I ask you to recommend a good place to visit?"},
    {"ID": "H1ENGA08B02C03", "Desc": "도움 필요 여부 묻기,Do you need any help?,Is there anything else I can do to help you?,If you need any help, just ask."},
    {"ID": "H1ENGA08B02C04", "Desc": "도움 제안하기,Let me carry it for you.,I'd be happy to help you with that."},
    {"ID": "H1ENGA08B03C05", "Desc": "고민이나 문제 표현하기,I'm not sure how to handle this problem.,I have trouble sleeping at night."},
    {"ID": "H1ENGA08B03C06", "Desc": "조언 묻기,Can I get your advice on ways to stay more positive?,Could you share some tips on how to prepare for the interview?,How can I improve my public speaking skills?"},
    {"ID": "H1ENGA08B04C07", "Desc": "조언하기,I think you should set clear goals.,It would be helpful for you to practice more.,I recommend that you share your feelings with your friends.,It's important to stay positive."},
    {"ID": "H1ENGA08B04C08", "Desc": "격려하기,I believe that you will do better next time.,Relax and keep moving forward."},
    {"ID": "H1ENGA09B01C01", "Desc": "대화 장소 파악하기,library,museum,restaurant,airport,subway station,store,theater,hospital"},
    {"ID": "H1ENGA09B01C02", "Desc": "화자간의 관계 파악하기,friends,family members,teacher-student,customer-service provider,customer-store staff,doctor-patient"},
    {"ID": "H1ENGA09B02C03", "Desc": "글의 구조 파악하기,text structure,process,time order,description,compare/contrast,problem-solution,cause-effect,argument-support"},
    {"ID": "H1ENGA09B02C04", "Desc": "논리적 관계 파악하기,for instance,in conclusion,in contrast,however,therefore,as a result,moreover,similarly,in other words"},
    {"ID": "H1ENGA09B03C05", "Desc": "비유적 표현 이해하기,put a roof over someone's head"},
    {"ID": "H1ENGA09B03C06", "Desc": "관용어구 이해하기,piece of cake,in the same boat,white elephant,crocodile tears,make a beeline"}
]